# Generated by Django 5.1 on 2025-08-08 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jantina', models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('bangsa', models.CharField(choices=[('Melayu', 'Melayu'), ('India', 'India'), ('Cina', 'Cina'), ('Lain-lain', 'Lain-lain')], max_length=20)),
                ('umur', models.CharField(choices=[('18 - 25 tahun', '18 - 25 tahun'), ('26 - 39 tahun', '26 - 39 tahun'), ('40 - 59 tahun', '40 - 59 tahun'), ('60 dan ke atas', '60 dan ke atas')], max_length=20)),
                ('job', models.CharField(choices=[('Ahli Majlis, MBI', 'Ahli Majlis, MBI'), ('Kakitangan MBI', 'Kakitangan MBI'), ('Kakitangan Kerajaan', 'Kakitangan Kerajaan'), ('Kakitangan Swasta', 'Kakitangan Swasta'), ('Bekerja Sendiri', 'Bekerja Sendiri'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pelajar', 'Pelajar'), ('Pesara', 'Pesara')], max_length=50)),
                ('zon', models.CharField(blank=True, max_length=20, null=True)),
                ('cad', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submissions',
                'db_table': 'user_submissions',
            },
        ),
        migrations.CreateModel(
            name='SubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.IntegerField()),
                ('pilihan', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('butiran', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='userideabajet.usersubmission')),
            ],
            options={
                'db_table': 'submission_details',
            },
        ),
    ]
