# Generated by Django 5.1 on 2025-08-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminideabajet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aset',
            name='elemen5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminideabajet.elemen5'),
        ),
    ]
